language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install 4.0; fi

script:
  - swift --version
  - swift run test
