os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install 4.0
script:
  - swift --version
  - swift run test
